In [1]:
import numpy as np 
import matplotlib.pylab as plt 
import scipy as sc
import pandas as pd

In [2]:
def min_parameters(matriz,columna):
    c=matriz[::,columna]; 
    return matriz[c.argmin(),:]

In [3]:
def chi_min_2D(A,D,C): 
    
    C_min=np.array([0,0,0]);
    A_base=np.array(list(dict.fromkeys(A))); D_base=np.array(list(dict.fromkeys(D))); 
    A_base.sort(); D_base.sort(); 

    for i in range(0,A_base.size):
        for j in range(0,D_base.size): 
            C0=C.max()
            values= np.where(D==D_base[j])[0]
            for k in range(0,values.size): 
                if A[values[k]]==A_base[i] and D_base[j]==D[values[k]]: 
                    if C[values[k]]<C0: 
                        C0 = C[values[k]]
                    
            C_min=np.vstack([C_min,[A_base[i],D_base[j],C0]]) 
    return C_min[1:]  

In [4]:
def chi_min_1D(A,C): 
    C_min=np.array([0,0]);
    A_base=np.array(list(dict.fromkeys(A))); A_base.sort();
    
    for i in range(0,A_base.size):
        C0=C.max()
        values= np.where(A==A_base[i])[0]
        for k in range(0,values.size): 
            if A[values[k]]==A_base[i]: 
                if C[values[k]]<C0: 
                    C0 = C[values[k]]
                    
        C_min=np.vstack([C_min,[A_base[i],C0]]) 
    return C_min[1:]

In [5]:
dff=pd.read_csv('/home/miguel/Documentos/Wolfram Mathematica/HDE_Barrow_GO/chi2M_big.csv')

In [6]:
data=dff.get_values()

In [7]:
data[:,1] = data[:,1]-min_parameters(data,1)[1]

In [8]:
min_parameters(data,1)[1]

0.0

In [10]:
range_M=data[::,0]; chi2_dat=data[::,1]; 

In [11]:
min_parameters(data,1)

array([-17.097,   0.   ])

In [12]:
M_chi2=chi_min_1D(range_M,chi2_dat)

In [13]:
np.savetxt('/home/miguel/Documentos/Wolfram Mathematica/HDE_Barrow_GO/M2_py.csv',M_chi2,delimiter = ',')

---------------------------------------------------------------------------------------------

In [5]:
df=pd.read_csv('/home/miguel/Documentos/Wolfram Mathematica/HDE_Barrow_GO/mb.csv')

In [6]:
data=df.get_values()

In [7]:
data.sort(axis=0)

In [8]:
data

array([[1.01200000e-02, 1.38550647e+01],
       [1.03800000e-02, 1.39105779e+01],
       [1.04300000e-02, 1.39210952e+01],
       ...,
       [1.80000000e+00, 2.63218101e+01],
       [1.91400000e+00, 2.64852137e+01],
       [2.26000000e+00, 2.69256117e+01]])

In [9]:
np.savetxt('/home/miguel/Documentos/Wolfram Mathematica/HDE_Barrow_GO/mb_py.csv',data,delimiter = ',')

In [10]:
df2=pd.read_csv('/home/miguel/Documentos/Wolfram Mathematica/HDE_Barrow_GO/mb1sup.csv')

In [11]:
data2=df2.get_values()

In [12]:
data2.sort(axis=0)

In [13]:
np.savetxt('/home/miguel/Documentos/Wolfram Mathematica/HDE_Barrow_GO/mb1sup_py.csv',data2,delimiter = ',')

In [14]:
df3=pd.read_csv('/home/miguel/Documentos/Wolfram Mathematica/HDE_Barrow_GO/mb1sdown.csv')

In [15]:
data3=df3.get_values()

In [16]:
data3.sort(axis=0)

In [17]:
np.savetxt('/home/miguel/Documentos/Wolfram Mathematica/HDE_Barrow_GO/mb1sdown_py.csv',data3,delimiter = ',')

In [18]:
np.abs(data-data2)

array([[0.   , 0.013],
       [0.   , 0.013],
       [0.   , 0.013],
       ...,
       [0.   , 0.013],
       [0.   , 0.013],
       [0.   , 0.013]])

In [19]:
np.abs(data-data3)

array([[0.   , 0.012],
       [0.   , 0.012],
       [0.   , 0.012],
       ...,
       [0.   , 0.012],
       [0.   , 0.012],
       [0.   , 0.012]])