In [1]:
import numpy as np 
import matplotlib.pylab as plt 
import scipy as sc
import pandas as pd

In [2]:
def min_parameters(matriz,columna):
    c=matriz[::,columna]; 
    return matriz[c.argmin(),:]

In [3]:
def chi_min_2D(A,D,C): 
    
    C_min=np.array([0,0,0]);
    A_base=np.array(list(dict.fromkeys(A))); D_base=np.array(list(dict.fromkeys(D))); 
    A_base.sort(); D_base.sort(); 

    for i in range(0,A_base.size):
        for j in range(0,D_base.size): 
            C0=C.max()
            values= np.where(D==D_base[j])[0]
            for k in range(0,values.size): 
                if A[values[k]]==A_base[i] and D_base[j]==D[values[k]]: 
                    if C[values[k]]<C0: 
                        C0 = C[values[k]]
                    
            C_min=np.vstack([C_min,[A_base[i],D_base[j],C0]]) 
    return C_min[1:]  

In [4]:
def chi_min_1D(A,C): 
    C_min=np.array([0,0]);
    A_base=np.array(list(dict.fromkeys(A))); A_base.sort();
    
    for i in range(0,A_base.size):
        C0=C.max()
        values= np.where(A==A_base[i])[0]
        for k in range(0,values.size): 
            if A[values[k]]==A_base[i]: 
                if C[values[k]]<C0: 
                    C0 = C[values[k]]
                    
        C_min=np.vstack([C_min,[A_base[i],C0]]) 
    return C_min[1:]

In [5]:
dff=pd.read_csv('/home/miguel/Documentos/Wolfram Mathematica/HDE_Barrow_GO/DATABIG.csv')

In [6]:
data=dff.get_values()

In [7]:
data[:,3] = data[:,3]-min_parameters(data,3)[3]

In [12]:
data

array([[7.00000000e-01, 3.00000000e-01, 4.00000000e-04, 6.98900180e+01],
       [7.00000000e-01, 3.00000000e-01, 8.00000000e-04, 6.98323043e+01],
       [7.00000000e-01, 3.00000000e-01, 1.20000000e-03, 6.97796026e+01],
       ...,
       [1.00000000e+00, 9.00000000e-01, 2.92000000e-02, 4.94137298e+02],
       [1.00000000e+00, 9.00000000e-01, 2.96000000e-02, 2.34071880e+02],
       [1.00000000e+00, 9.00000000e-01, 3.00000000e-02, 3.29540699e+02]])

In [11]:
np.savetxt('/home/miguel/Documentos/Wolfram Mathematica/HDE_Barrow_GO/Data_py_big.dat',data,delimiter = ',')

In [13]:
range_alpha=data[::,0]; range_beta=data[::,1]; range_Delta=data[::,2]; chi2_dat=data[::,3]; 

In [10]:
min_parameters(data,3)

array([1.  , 0.69, 0.  , 0.  ])

In [17]:
range_beta[6956]

0.6

In [11]:
alpha_Delta_chi2=chi_min_2D(range_alpha,range_Delta,chi2_dat)

In [12]:
np.savetxt('/home/miguel/Documentos/Wolfram Mathematica/HDE_Barrow_GO/alpha_Delta_py_big.csv',alpha_Delta_chi2,delimiter = ',')

In [13]:
alpha_beta_chi2=chi_min_2D(range_alpha,range_beta,chi2_dat)

In [14]:
np.savetxt('/home/miguel/Documentos/Wolfram Mathematica/HDE_Barrow_GO/alpha_beta_py_big.csv',alpha_beta_chi2,delimiter = ',')

In [15]:
beta_Delta_chi2=chi_min_2D(range_beta,range_Delta,chi2_dat)

In [16]:
np.savetxt('/home/miguel/Documentos/Wolfram Mathematica/HDE_Barrow_GO/beta_Delta_py_big.csv',beta_Delta_chi2,delimiter = ',')

In [17]:
min_parameters(chi_min_2D(range_alpha,range_beta,chi2_dat),2)

array([1.  , 0.69, 0.  ])

In [18]:
alpha_chi2=chi_min_1D(range_alpha,chi2_dat)

In [19]:
np.savetxt('/home/miguel/Documentos/Wolfram Mathematica/HDE_Barrow_GO/alphapy_big.csv',alpha_chi2,delimiter = ',')

In [20]:
beta_chi2=chi_min_1D(range_beta,chi2_dat)

In [21]:
np.savetxt('/home/miguel/Documentos/Wolfram Mathematica/HDE_Barrow_GO/betapy_big.csv',beta_chi2,delimiter = ',')

In [22]:
Delta_chi2=chi_min_1D(range_Delta,chi2_dat)

In [23]:
np.savetxt('/home/miguel/Documentos/Wolfram Mathematica/HDE_Barrow_GO/Deltapy_big.csv',Delta_chi2,delimiter = ',')